WorkScheduler/Models/Service.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WorkScheduler.Models
{
    public enum Status { NotAssigned, Waiting, InProgress, Cancelled, Done }
    public enum Priority { Low, Normal, High }
    public class Service
    {
        public int ServiceId { get; set; }
        public int? OrderId { get; set; }
        public virtual Order Order { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public string AssignedEmployeeId { get; set; }
        public virtual ApplicationUser AssignedEmployee { get; set; }
        public Priority Priority { get; set; }
        public Status Status { get; set; }

        public TimeSpan? Duration { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime? Deadline { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime? StartTime { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime? EndTime { get; set; }

        void AssignEmployee(ApplicationUser employee)
        {
            AssignedEmployee = employee;
            Status = Status.Waiting;
        }
        void CalculateEndTime()
        {
            EndTime = StartTime + Duration;
        }
    }
}

WorkScheduler/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkScheduler.Models;
using Microsoft.AspNet.Identity;

namespace WorkScheduler.Controllers
{
    public class ServicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private string FindEmployeeIdWithLeastWorkAssigned()
        {
            var __debug_0 = db.Services
                .Where(x => x.AssignedEmployee.Position == Position.ProductionWorker)
                .ToList();

            var __debug_1 = db.Services
                .Where(x => x.AssignedEmployee.Position == Position.CustomerService)
                .ToList();

            var userId = db.Services
                .Where(x => x.AssignedEmployee.Position == Position.ProductionWorker)
                .GroupBy(x => x.AssignedEmployeeId)
                .Select(x => new
                {
                    AssignedEmployeeId = x.Key,
                    EndTime = x.Max(s => s.EndTime)
                })
                .OrderBy(x => x.EndTime)
                .Select(x => x.AssignedEmployeeId)
                .FirstOrDefault();

            var userWithoutAnyService = db.Users
                .Where(x => x.Position == Position.ProductionWorker)
                .Where(x => x.Services.Count() == 0)
                .FirstOrDefault();

            if (userWithoutAnyService != null)
            {
                return userWithoutAnyService.Id;
            }
            else
            {
                return userId;
            }
        }

        private DateTime? getEndTimeOfLastService(string userId)
        {
            var endTimeOfLastService = db.Services
                .Where(x => x.AssignedEmployee.Id == userId)
                .OrderByDescending(x => x.EndTime)
                .Select(x => x.EndTime)
                .FirstOrDefault();

            return endTimeOfLastService;
        }

        // GET: Services
        public async Task<ActionResult> Index()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);
            var services = await db.Services.ToListAsync();
            if (currentUser.Position == Position.ProductionWorker)
            {
                return View(services.Where(x => x.AssignedEmployee == currentUser).OrderByDescending(x => x.StartTime));
            }
            else
            {
                return View(services.OrderByDescending(x => x.StartTime));
            }
        }

        // GET: Services/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = await db.Services.FindAsync(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateForOrder(int orderId)
        {
            Service service = new Service { OrderId = orderId };
            //Order order = new Order { OrderId = orderId };
            return View("Create", service);
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ServiceId,Name,Description,Cost,Priority,Status,Duration,Deadline,StartTime,EndTime,OrderId")] Service service)
        {
            if (ModelState.IsValid)
            {
                /*
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault
                    (x => x.Id == currentUserId);
                service.AssignedEmployee = currentUser;
                */
                service.Status = Status.NotAssigned;

                // Find and assign employee with least work
                string employeeIdWithLeastWork = FindEmployeeIdWithLeastWorkAssigned();
                service.AssignedEmployee = db.Users.FirstOrDefault
                    (x => x.Id == employeeIdWithLeastWork);
                service.AssignedEmployeeId = service.AssignedEmployee.Id;
                service.Status = Status.Waiting;

                // Calculate start and end time 
                var EndTimeOfLastTask = getEndTimeOfLastService(service.AssignedEmployeeId);
                if (EndTimeOfLastTask == null || EndTimeOfLastTask < DateTime.Now)
                {
                    EndTimeOfLastTask = DateTime.Now;
                }       
                service.StartTime = EndTimeOfLastTask;
                service.EndTime = service.StartTime + service.Duration;

                db.Services.Add(service);
                await db.SaveChangesAsync();

                if (service.OrderId.HasValue)
                {
                    return RedirectToAction("Edit", "Orders", new { id = service.OrderId });
                }

                return RedirectToAction("Index");
            }

            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = await db.Services.FindAsync(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ServiceId,Name,Description,Cost,Priority,Status,Duration,Deadline,StartTime,EndTime,OrderId")] Service service)
        {
            if (ModelState.IsValid)
            {
                //var db.Services.Where(s => s.ServiceId == service.ServiceId).FirstOrDefault();
                db.Entry(service).State = EntityState.Modified;
                await db.SaveChangesAsync();
                if (service.OrderId.HasValue)
                {
                    return RedirectToAction("Edit", "Orders", new { id = service.OrderId });
                }
                return RedirectToAction("Index");
            }
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = await db.Services.FindAsync(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            
            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Service service = await db.Services.FindAsync(id);
            db.Services.Remove(service);
            await db.SaveChangesAsync();
            if (service.OrderId.HasValue)
            {
                return RedirectToAction("Edit", "Orders", new { id = service.OrderId });
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorkScheduler/Views/Services/Create.cshtml
@model WorkScheduler.Models.Service

@{
    ViewBag.Title = "Create";
}

<h2>Create service</h2>


@using (Html.BeginForm("Create", "Services", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Priority, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
        </div>
    </div>

    <script>
        var date = new Date();
        date.setHours(1);
        date.setMinutes(0);
        $(function () {
            $('#Duration').datetimepicker(
                {
                    format: 'HH:mm',
                    defaultDate: date,
                    showClear: true
                });
        });
    </script>

    <div class="form-group">
        @Html.LabelFor(model => model.Deadline, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Deadline, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Deadline, "", new { @class = "text-danger" })
        </div>
    </div>

    <script>
        $(function () {
            $('#Deadline').datetimepicker(
                {
                    format: 'DD-MM-YYYY HH:mm'
                });
        });
    </script>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.HiddenFor(s => s.OrderId)
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    @Scripts.Render("~/Content/bootstrap-datetimepicker")
}

WorkScheduler/Views/Services/Delete.cshtml
@model WorkScheduler.Models.Service

@{
    ViewBag.Title = "Delete";
}

<h2>Delete service</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deadline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @Html.HiddenFor(s => s.OrderId)
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>
    }
</div>

WorkScheduler/Views/Services/Details.cshtml
@model WorkScheduler.Models.Service

@{
    ViewBag.Title = "Details";
}

<h2>Service details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deadline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ServiceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WorkScheduler/Views/Services/Edit.cshtml
@model WorkScheduler.Models.Service

@{
    ViewBag.Title = "Edit";
}

<h2>Edit service</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ServiceId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Priority, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deadline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deadline, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deadline, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.HiddenFor(s => s.OrderId)
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkScheduler/Views/Services/Index.cshtml
@model IEnumerable<WorkScheduler.Models.Service>

@{
    ViewBag.Title = "Service list";
}

<h2>Service list</h2>

<p>
    @Html.ActionLink("New service", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            Employee
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deadline)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priority)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <th>
            @Html.DisplayFor(model => item.AssignedEmployee.FirstName) @Html.DisplayFor(model => item.AssignedEmployee.LastName)
        </th>
        <td>
            @Html.DisplayFor(modelItem => item.Duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Deadline)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ServiceId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ServiceId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ServiceId })
        </td>
    </tr>
}

</table>